version: '3.9'

services:
  fastapi:
    build:
      context: ./customer_churn_app_fastapi  # Directory containing FastAPI Dockerfile
    container_name: fastapi_service
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi_app:/app
    networks:
      - app-network

  streamlit:
    build:
      context: ./customer_churn_app_streamlit  # Directory containing Streamlit Dockerfile
    container_name: streamlit_service
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit_app:/app
    depends_on:
      - fastapi
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

